### PR TITLE
else removal

### PR DESCRIPTION
**Pull request by piyush2dev**

### CODE REVIEW

**Comment by deepshikha6464** [comment]
didnt ask for ur wise opinion

**Comment by piyush2dev** [comment]
Yeah. Apology for that but can I contribute in your GitHub repo, please. They seems interesting.

**Comment by deepshikha6464** [comment]
no

**Comment by piyush2dev** [comment]
Sure. I will not.
R u willing to participate as team in this Hackathon. https://www.sih.gov.in/

**Comment by deepshikha6464** [comment]
why dont you try this hackathon gimmick on any other fresher

**Comment by piyush2dev** [comment]
Arrey asking seriously. Not for a gimmick. It's ok if u don't want to.

**Pull request closed without merging**
